name: 'build'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Run build script
        id: build
        run: |
          ./build_image.sh
      - name: Check outputs
        run: |
          ls -l
      - name: Upload full image
        uses: actions/upload-artifact@v6
        id: rcn_os
        with:
          name: rcn_os
          path: |
            rcn_os.img.gz
            rcn_os.img.gz.sha256
          if-no-files-found: error
      - name: Upload update
        uses: actions/upload-artifact@v6
        id: rcn_os_update
        with:
          name: rcn_os_update
          path: |
            rcn_os_update.img.gz
            rcn_os_update.img.gz.sha256
          if-no-files-found: error
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload full image to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            rcn_os.img.gz
          asset_content_type: application/gzip
      - name: Upload full image sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            rcn_os.img.gz.sha256
          asset_content_type: text/plain
      - name: Upload update image to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            rcn_os_update.img.gz
          asset_content_type: application/gzip
      - name: Upload update image sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            rcn_os_update.img.gz.sha256
          asset_content_type: text/plain
