name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Run build script
        id: build
        run: |
          ./build_image.sh
      - name: Check outputs and ungzip
        run: |
          gunzip rcn_os.img.gz
          gunzip rcn_os_update.img.gz
          ls -l
      - name: Upload full image
        uses: actions/upload-artifact@v6
        with:
          name: rcn_os
          path: |
            rcn_os.img
      - name: Upload update
        uses: actions/upload-artifact@v6
        with:
          name: rcn_os_update
          path: |
            rcn_os_update.img
          if-no-files-found: error
